---
title: "BudgetImpact"
output: 
  flexdashboard::flex_dashboard:
    orientation: columns
runtime: shiny
---

```{r global, include=FALSE}
# load data in 'global' chunk so it can be shared by all users of the dashboard
library(DT)
library(tidyverse)
library(ggplot2)
library(mgcv)
library(magrittr)

```

Sidebar {.sidebar}
=====================================
```{r}
# There are 3 input buttons
values <- reactiveValues(varA = NULL,
                         varB = NULL,
                         varC = NULL)

selectInput('input1', 'Input 1', c("A","B"))
selectInput('input2', 'Input 2', c("A","B"))
selectInput('input3', 'Input 3', c("A","B"))
```

Welcome
=====================================  
### Panel A  {data-height=300}
test test test
```{r}
#renderTable(values$varA,
#          fillContainer = FALSE)

```

### Panel B: {data-height=150}
```{r}

```

### Panel C
```{r}


```


Population
=====================================  
### Panel A  {data-height=300}
```{r}
#renderTable(values$varA,
#          fillContainer = FALSE)

```


Uptake
=====================================  
### Panel A  {data-height=300}
```{r}
#renderTable(values$varA,
#          fillContainer = FALSE)

```


Cost
=====================================  
### Panel A  {data-height=300}
```{r}
#renderTable(values$varA,
#          fillContainer = FALSE)

```


Calculations
=====================================  
### Panel A  {data-height=300}
```{r}
#renderTable(values$varA,
#          fillContainer = FALSE)

```


Results
=====================================  
### Panel A  {data-height=300}
```{r}
#renderTable(values$varA,
#          fillContainer = FALSE)

```


#Calculate net budget impact

